import { useState } from 'react';
import { Download, Share2 } from 'lucide-react';
import { useAuth } from '@/lib/auth-context';
import { AppShell, PageHeader } from './AppShell';
import { Alert, Button } from './ui';

export function DataBackupScreen() {
  const { user } = useAuth();
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [generating, setGenerating] = useState(false);
  const [done, setDone] = useState(false);

  const categories = [
    'Pupil Records', 'Staff Records', 'Attendance Records',
    'Academic Records and Report Cards', 'Levy Records and Payments',
    'Incident Logs', 'Leave Records', 'Event Calendar',
    'Broadcast and Announcement History', 'All of the Above',
  ];

  function toggle(c: string) {
    setSelected((prev) => {
      const n = new Set(prev);
      if (n.has(c)) n.delete(c); else n.add(c);
      return n;
    });
  }

  async function generate() {
    setGenerating(true);
    const lines = [
      `SchoolPortal-GES Backup`,
      `School: ${user?.school_id ?? 'Platform'}`,
      `Date: ${new Date().toISOString()}`,
      `Categories: ${[...selected].join(', ')}`,
      `Generated by: ${user?.full_name ?? '—'}`,
      '',
      'This is a backup manifest. Full data export connects to the live database.',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SchoolPortal-GES_Backup_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setGenerating(false);
    setDone(true);
    setTimeout(() => setDone(false), 5000);
  }

  return (
    <AppShell title="Data Backup and Export">
      <PageHeader title="Data Backup" />
      {done && <div className="mb-4"><Alert type="success">Backup generated and downloaded.</Alert></div>}
      <p className="mb-4 text-sm text-gray-500">Select categories to export. The backup is generated locally from the database.</p>
      <div className="mb-4 space-y-2">
        {categories.map((c) => (
          <label key={c} className="flex items-center gap-3 rounded-lg border border-gray-200 p-3 dark:border-gray-800">
            <input type="checkbox" checked={selected.has(c)} onChange={() => toggle(c)} className="h-5 w-5 rounded" />
            <span className="text-sm text-gray-700 dark:text-gray-300">{c}</span>
          </label>
        ))}
      </div>
      <div className="flex gap-2">
        <Button onClick={generate} loading={generating} disabled={selected.size === 0}><Download size={16} /> Generate Backup</Button>
        <Button variant="secondary" disabled={!done}><Share2 size={16} /> Share</Button>
      </div>
    </AppShell>
  );
}
